package cn.com.taiji.domain;

import javax.validation.constraints.Max;
import javax.validation.constraints.Size;
import java.math.BigDecimal;
import java.util.Date;

public class Device {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max = 40 , message = "{id.length.error}")
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_name
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max = 100 , message = "{name.length.error}")
    private String deviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_type_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String deviceTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_status_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String deviceStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_status
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String deviceStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_purchase_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date devicePurchaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_purchase_price
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Max(value = 999999999 , message = "单价的长度限制在10个字符以内")
    private BigDecimal devicePurchasePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_manufacture_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date deviceManufactureDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_service_life
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date deviceServiceLife;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.device_keeper_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String deviceKeeperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max = 5000 , message = "{note.length.error}")
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_id
     *
     * @return the value of device.device_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_id
     *
     * @param deviceId the value for device.device_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_name
     *
     * @return the value of device.device_name
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_name
     *
     * @param deviceName the value for device.device_name
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_type_id
     *
     * @return the value of device.device_type_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getDeviceTypeId() {
        return deviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_type_id
     *
     * @param deviceTypeId the value for device.device_type_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDeviceTypeId(String deviceTypeId) {
        this.deviceTypeId = deviceTypeId == null ? null : deviceTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_status_id
     *
     * @return the value of device.device_status_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getDeviceStatusId() {
        return deviceStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_status_id
     *
     * @param deviceStatusId the value for device.device_status_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDeviceStatusId(String deviceStatusId) {
        this.deviceStatusId = deviceStatusId == null ? null : deviceStatusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_status
     *
     * @return the value of device.device_status
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getDeviceStatus() {
        return deviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_status
     *
     * @param deviceStatus the value for device.device_status
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDeviceStatus(String deviceStatus) {
        this.deviceStatus = deviceStatus == null ? null : deviceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_purchase_date
     *
     * @return the value of device.device_purchase_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getDevicePurchaseDate() {
        return devicePurchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_purchase_date
     *
     * @param devicePurchaseDate the value for device.device_purchase_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDevicePurchaseDate(Date devicePurchaseDate) {
        this.devicePurchaseDate = devicePurchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_purchase_price
     *
     * @return the value of device.device_purchase_price
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public BigDecimal getDevicePurchasePrice() {
        return devicePurchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_purchase_price
     *
     * @param devicePurchasePrice the value for device.device_purchase_price
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDevicePurchasePrice(BigDecimal devicePurchasePrice) {
        this.devicePurchasePrice = devicePurchasePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_manufacture_date
     *
     * @return the value of device.device_manufacture_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getDeviceManufactureDate() {
        return deviceManufactureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_manufacture_date
     *
     * @param deviceManufactureDate the value for device.device_manufacture_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDeviceManufactureDate(Date deviceManufactureDate) {
        this.deviceManufactureDate = deviceManufactureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_service_life
     *
     * @return the value of device.device_service_life
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getDeviceServiceLife() {
        return deviceServiceLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_service_life
     *
     * @param deviceServiceLife the value for device.device_service_life
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDeviceServiceLife(Date deviceServiceLife) {
        this.deviceServiceLife = deviceServiceLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.device_keeper_id
     *
     * @return the value of device.device_keeper_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getDeviceKeeperId() {
        return deviceKeeperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.device_keeper_id
     *
     * @param deviceKeeperId the value for device.device_keeper_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDeviceKeeperId(String deviceKeeperId) {
        this.deviceKeeperId = deviceKeeperId == null ? null : deviceKeeperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.note
     *
     * @return the value of device.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.note
     *
     * @param note the value for device.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}