package cn.com.taiji.domain;

import java.math.BigDecimal;
import java.util.Date;

public class FinalCountCheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.f_count_check_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String fCountCheckId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.order_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.check_item
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String checkItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.sample
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer sample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.check_number
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer checkNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.unqualify
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer unqualify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.qualify
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private BigDecimal qualify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.cdate
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date cdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.measure_data
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String measureData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.emp_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.result
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column final_count_check.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.f_count_check_id
     *
     * @return the value of final_count_check.f_count_check_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getfCountCheckId() {
        return fCountCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.f_count_check_id
     *
     * @param fCountCheckId the value for final_count_check.f_count_check_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setfCountCheckId(String fCountCheckId) {
        this.fCountCheckId = fCountCheckId == null ? null : fCountCheckId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.order_id
     *
     * @return the value of final_count_check.order_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.order_id
     *
     * @param orderId the value for final_count_check.order_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.check_item
     *
     * @return the value of final_count_check.check_item
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getCheckItem() {
        return checkItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.check_item
     *
     * @param checkItem the value for final_count_check.check_item
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setCheckItem(String checkItem) {
        this.checkItem = checkItem == null ? null : checkItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.sample
     *
     * @return the value of final_count_check.sample
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getSample() {
        return sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.sample
     *
     * @param sample the value for final_count_check.sample
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setSample(Integer sample) {
        this.sample = sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.check_number
     *
     * @return the value of final_count_check.check_number
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getCheckNumber() {
        return checkNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.check_number
     *
     * @param checkNumber the value for final_count_check.check_number
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setCheckNumber(Integer checkNumber) {
        this.checkNumber = checkNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.unqualify
     *
     * @return the value of final_count_check.unqualify
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getUnqualify() {
        return unqualify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.unqualify
     *
     * @param unqualify the value for final_count_check.unqualify
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setUnqualify(Integer unqualify) {
        this.unqualify = unqualify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.qualify
     *
     * @return the value of final_count_check.qualify
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public BigDecimal getQualify() {
        return qualify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.qualify
     *
     * @param qualify the value for final_count_check.qualify
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setQualify(BigDecimal qualify) {
        this.qualify = qualify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.cdate
     *
     * @return the value of final_count_check.cdate
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.cdate
     *
     * @param cdate the value for final_count_check.cdate
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.measure_data
     *
     * @return the value of final_count_check.measure_data
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getMeasureData() {
        return measureData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.measure_data
     *
     * @param measureData the value for final_count_check.measure_data
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setMeasureData(String measureData) {
        this.measureData = measureData == null ? null : measureData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.emp_id
     *
     * @return the value of final_count_check.emp_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.emp_id
     *
     * @param empId the value for final_count_check.emp_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.result
     *
     * @return the value of final_count_check.result
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.result
     *
     * @param result the value for final_count_check.result
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column final_count_check.note
     *
     * @return the value of final_count_check.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column final_count_check.note
     *
     * @param note the value for final_count_check.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}