package cn.com.taiji.domain;

import java.util.Date;

public class Manufacture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacture.manufacture_sn
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String manufactureSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacture.order_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacture.technology_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String technologyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacture.launch_quantity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer launchQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacture.begin_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacture.end_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacture.manufacture_sn
     *
     * @return the value of manufacture.manufacture_sn
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getManufactureSn() {
        return manufactureSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacture.manufacture_sn
     *
     * @param manufactureSn the value for manufacture.manufacture_sn
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setManufactureSn(String manufactureSn) {
        this.manufactureSn = manufactureSn == null ? null : manufactureSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacture.order_id
     *
     * @return the value of manufacture.order_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacture.order_id
     *
     * @param orderId the value for manufacture.order_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacture.technology_id
     *
     * @return the value of manufacture.technology_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getTechnologyId() {
        return technologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacture.technology_id
     *
     * @param technologyId the value for manufacture.technology_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setTechnologyId(String technologyId) {
        this.technologyId = technologyId == null ? null : technologyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacture.launch_quantity
     *
     * @return the value of manufacture.launch_quantity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getLaunchQuantity() {
        return launchQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacture.launch_quantity
     *
     * @param launchQuantity the value for manufacture.launch_quantity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setLaunchQuantity(Integer launchQuantity) {
        this.launchQuantity = launchQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacture.begin_date
     *
     * @return the value of manufacture.begin_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacture.begin_date
     *
     * @param beginDate the value for manufacture.begin_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacture.end_date
     *
     * @return the value of manufacture.end_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacture.end_date
     *
     * @param endDate the value for manufacture.end_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}