package cn.com.taiji.domain;

import java.util.Date;

public class MaterialConsume {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_consume.consume_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String consumeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_consume.work_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String workId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_consume.material_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String materialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_consume.consume_amount
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer consumeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_consume.consume_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date consumeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_consume.sender
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_consume.receiver
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_consume.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_consume.consume_id
     *
     * @return the value of material_consume.consume_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getConsumeId() {
        return consumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_consume.consume_id
     *
     * @param consumeId the value for material_consume.consume_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setConsumeId(String consumeId) {
        this.consumeId = consumeId == null ? null : consumeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_consume.work_id
     *
     * @return the value of material_consume.work_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_consume.work_id
     *
     * @param workId the value for material_consume.work_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_consume.material_id
     *
     * @return the value of material_consume.material_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_consume.material_id
     *
     * @param materialId the value for material_consume.material_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setMaterialId(String materialId) {
        this.materialId = materialId == null ? null : materialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_consume.consume_amount
     *
     * @return the value of material_consume.consume_amount
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getConsumeAmount() {
        return consumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_consume.consume_amount
     *
     * @param consumeAmount the value for material_consume.consume_amount
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setConsumeAmount(Integer consumeAmount) {
        this.consumeAmount = consumeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_consume.consume_date
     *
     * @return the value of material_consume.consume_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getConsumeDate() {
        return consumeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_consume.consume_date
     *
     * @param consumeDate the value for material_consume.consume_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setConsumeDate(Date consumeDate) {
        this.consumeDate = consumeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_consume.sender
     *
     * @return the value of material_consume.sender
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_consume.sender
     *
     * @param sender the value for material_consume.sender
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_consume.receiver
     *
     * @return the value of material_consume.receiver
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_consume.receiver
     *
     * @param receiver the value for material_consume.receiver
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_consume.note
     *
     * @return the value of material_consume.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_consume.note
     *
     * @param note the value for material_consume.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}