package cn.com.taiji.domain;

public class Process {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.process_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.technology_plan_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String technologyPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.sequence
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.quota
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer quota;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.process_id
     *
     * @return the value of process.process_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.process_id
     *
     * @param processId the value for process.process_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.technology_plan_id
     *
     * @return the value of process.technology_plan_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getTechnologyPlanId() {
        return technologyPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.technology_plan_id
     *
     * @param technologyPlanId the value for process.technology_plan_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setTechnologyPlanId(String technologyPlanId) {
        this.technologyPlanId = technologyPlanId == null ? null : technologyPlanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.sequence
     *
     * @return the value of process.sequence
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.sequence
     *
     * @param sequence the value for process.sequence
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.quota
     *
     * @return the value of process.quota
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getQuota() {
        return quota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.quota
     *
     * @param quota the value for process.quota
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setQuota(Integer quota) {
        this.quota = quota;
    }
}