package cn.com.taiji.domain;

import java.util.Date;

public class ProcessMeasureCheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_measure_check.p_measure_check_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String pMeasureCheckId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_measure_check.process_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_measure_check.check_item
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String checkItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_measure_check.cdate
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date cdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_measure_check.measure_data
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String measureData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_measure_check.emp_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_measure_check.result
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process_measure_check.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_measure_check.p_measure_check_id
     *
     * @return the value of process_measure_check.p_measure_check_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getpMeasureCheckId() {
        return pMeasureCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_measure_check.p_measure_check_id
     *
     * @param pMeasureCheckId the value for process_measure_check.p_measure_check_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setpMeasureCheckId(String pMeasureCheckId) {
        this.pMeasureCheckId = pMeasureCheckId == null ? null : pMeasureCheckId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_measure_check.process_id
     *
     * @return the value of process_measure_check.process_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_measure_check.process_id
     *
     * @param processId the value for process_measure_check.process_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_measure_check.check_item
     *
     * @return the value of process_measure_check.check_item
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getCheckItem() {
        return checkItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_measure_check.check_item
     *
     * @param checkItem the value for process_measure_check.check_item
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setCheckItem(String checkItem) {
        this.checkItem = checkItem == null ? null : checkItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_measure_check.cdate
     *
     * @return the value of process_measure_check.cdate
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_measure_check.cdate
     *
     * @param cdate the value for process_measure_check.cdate
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_measure_check.measure_data
     *
     * @return the value of process_measure_check.measure_data
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getMeasureData() {
        return measureData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_measure_check.measure_data
     *
     * @param measureData the value for process_measure_check.measure_data
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setMeasureData(String measureData) {
        this.measureData = measureData == null ? null : measureData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_measure_check.emp_id
     *
     * @return the value of process_measure_check.emp_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_measure_check.emp_id
     *
     * @param empId the value for process_measure_check.emp_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_measure_check.result
     *
     * @return the value of process_measure_check.result
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_measure_check.result
     *
     * @param result the value for process_measure_check.result
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process_measure_check.note
     *
     * @return the value of process_measure_check.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process_measure_check.note
     *
     * @param note the value for process_measure_check.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}