package cn.com.taiji.domain;

import java.math.BigDecimal;

public class Technology {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.technology_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String technologyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.technology_name
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String technologyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.price
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.vital_process_period
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String vitalProcessPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.standard_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer standardCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.overtime_standard_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer overtimeStandardCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.overtime_overfulfil_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer overtimeOverfulfilCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.double_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer doubleCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology.overfulfil_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer overfulfilCapacity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.technology_id
     *
     * @return the value of technology.technology_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getTechnologyId() {
        return technologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.technology_id
     *
     * @param technologyId the value for technology.technology_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setTechnologyId(String technologyId) {
        this.technologyId = technologyId == null ? null : technologyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.technology_name
     *
     * @return the value of technology.technology_name
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getTechnologyName() {
        return technologyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.technology_name
     *
     * @param technologyName the value for technology.technology_name
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setTechnologyName(String technologyName) {
        this.technologyName = technologyName == null ? null : technologyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.price
     *
     * @return the value of technology.price
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.price
     *
     * @param price the value for technology.price
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.vital_process_period
     *
     * @return the value of technology.vital_process_period
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getVitalProcessPeriod() {
        return vitalProcessPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.vital_process_period
     *
     * @param vitalProcessPeriod the value for technology.vital_process_period
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setVitalProcessPeriod(String vitalProcessPeriod) {
        this.vitalProcessPeriod = vitalProcessPeriod == null ? null : vitalProcessPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.standard_capacity
     *
     * @return the value of technology.standard_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getStandardCapacity() {
        return standardCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.standard_capacity
     *
     * @param standardCapacity the value for technology.standard_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setStandardCapacity(Integer standardCapacity) {
        this.standardCapacity = standardCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.overtime_standard_capacity
     *
     * @return the value of technology.overtime_standard_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getOvertimeStandardCapacity() {
        return overtimeStandardCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.overtime_standard_capacity
     *
     * @param overtimeStandardCapacity the value for technology.overtime_standard_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setOvertimeStandardCapacity(Integer overtimeStandardCapacity) {
        this.overtimeStandardCapacity = overtimeStandardCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.overtime_overfulfil_capacity
     *
     * @return the value of technology.overtime_overfulfil_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getOvertimeOverfulfilCapacity() {
        return overtimeOverfulfilCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.overtime_overfulfil_capacity
     *
     * @param overtimeOverfulfilCapacity the value for technology.overtime_overfulfil_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setOvertimeOverfulfilCapacity(Integer overtimeOverfulfilCapacity) {
        this.overtimeOverfulfilCapacity = overtimeOverfulfilCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.double_capacity
     *
     * @return the value of technology.double_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getDoubleCapacity() {
        return doubleCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.double_capacity
     *
     * @param doubleCapacity the value for technology.double_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDoubleCapacity(Integer doubleCapacity) {
        this.doubleCapacity = doubleCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology.overfulfil_capacity
     *
     * @return the value of technology.overfulfil_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getOverfulfilCapacity() {
        return overfulfilCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology.overfulfil_capacity
     *
     * @param overfulfilCapacity the value for technology.overfulfil_capacity
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setOverfulfilCapacity(Integer overfulfilCapacity) {
        this.overfulfilCapacity = overfulfilCapacity;
    }
}