package cn.com.taiji.domain;

import javax.validation.constraints.Max;
import javax.validation.constraints.Size;
import java.util.Date;

public class TechnologyPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_plan.technology_plan_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max = 40 , message = "{id.length.error}")
    private String technologyPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_plan.technology_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String technologyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_plan.batch_amount
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Max(value = 99999999 , message = "批次数量不能超过99999999")
    private Integer batchAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_plan.start_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date startPlan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_plan.end_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date endPlan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_plan.commit_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date commitPlan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_plan.technology_plan_start
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date technologyPlanStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_plan.technology_plan_end
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date technologyPlanEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology_plan.technology_plan_id
     *
     * @return the value of technology_plan.technology_plan_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getTechnologyPlanId() {
        return technologyPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology_plan.technology_plan_id
     *
     * @param technologyPlanId the value for technology_plan.technology_plan_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setTechnologyPlanId(String technologyPlanId) {
        this.technologyPlanId = technologyPlanId == null ? null : technologyPlanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology_plan.technology_id
     *
     * @return the value of technology_plan.technology_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getTechnologyId() {
        return technologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology_plan.technology_id
     *
     * @param technologyId the value for technology_plan.technology_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setTechnologyId(String technologyId) {
        this.technologyId = technologyId == null ? null : technologyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology_plan.batch_amount
     *
     * @return the value of technology_plan.batch_amount
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getBatchAmount() {
        return batchAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology_plan.batch_amount
     *
     * @param batchAmount the value for technology_plan.batch_amount
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setBatchAmount(Integer batchAmount) {
        this.batchAmount = batchAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology_plan.start_plan
     *
     * @return the value of technology_plan.start_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getStartPlan() {
        return startPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology_plan.start_plan
     *
     * @param startPlan the value for technology_plan.start_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setStartPlan(Date startPlan) {
        this.startPlan = startPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology_plan.end_plan
     *
     * @return the value of technology_plan.end_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getEndPlan() {
        return endPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology_plan.end_plan
     *
     * @param endPlan the value for technology_plan.end_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setEndPlan(Date endPlan) {
        this.endPlan = endPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology_plan.commit_plan
     *
     * @return the value of technology_plan.commit_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getCommitPlan() {
        return commitPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology_plan.commit_plan
     *
     * @param commitPlan the value for technology_plan.commit_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setCommitPlan(Date commitPlan) {
        this.commitPlan = commitPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology_plan.technology_plan_start
     *
     * @return the value of technology_plan.technology_plan_start
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getTechnologyPlanStart() {
        return technologyPlanStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology_plan.technology_plan_start
     *
     * @param technologyPlanStart the value for technology_plan.technology_plan_start
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setTechnologyPlanStart(Date technologyPlanStart) {
        this.technologyPlanStart = technologyPlanStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology_plan.technology_plan_end
     *
     * @return the value of technology_plan.technology_plan_end
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getTechnologyPlanEnd() {
        return technologyPlanEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology_plan.technology_plan_end
     *
     * @param technologyPlanEnd the value for technology_plan.technology_plan_end
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setTechnologyPlanEnd(Date technologyPlanEnd) {
        this.technologyPlanEnd = technologyPlanEnd;
    }
}