package cn.com.taiji.domain;

import javax.validation.constraints.Max;
import javax.validation.constraints.Size;
import java.util.Date;

public class UnqualifyApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualify_apply.unqualify_apply_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max=40, message="{id.length.error}")
    private String unqualifyApplyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualify_apply.product_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualify_apply.unqualify_item
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max=200, message="不合格项目长度限制在200个字符之内")
    private String unqualifyItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualify_apply.unqualify_count
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Max(value=999999999, message="不合格数量不能超过999999999")
    private Integer unqualifyCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualify_apply.assembly_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date assemblyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualify_apply.emp_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private String empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualify_apply.apply_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Date applyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unqualify_apply.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max=5000, message="{note.length.error}")
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualify_apply.unqualify_apply_id
     *
     * @return the value of unqualify_apply.unqualify_apply_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getUnqualifyApplyId() {
        return unqualifyApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualify_apply.unqualify_apply_id
     *
     * @param unqualifyApplyId the value for unqualify_apply.unqualify_apply_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setUnqualifyApplyId(String unqualifyApplyId) {
        this.unqualifyApplyId = unqualifyApplyId == null ? null : unqualifyApplyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualify_apply.product_id
     *
     * @return the value of unqualify_apply.product_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualify_apply.product_id
     *
     * @param productId the value for unqualify_apply.product_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualify_apply.unqualify_item
     *
     * @return the value of unqualify_apply.unqualify_item
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getUnqualifyItem() {
        return unqualifyItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualify_apply.unqualify_item
     *
     * @param unqualifyItem the value for unqualify_apply.unqualify_item
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setUnqualifyItem(String unqualifyItem) {
        this.unqualifyItem = unqualifyItem == null ? null : unqualifyItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualify_apply.unqualify_count
     *
     * @return the value of unqualify_apply.unqualify_count
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getUnqualifyCount() {
        return unqualifyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualify_apply.unqualify_count
     *
     * @param unqualifyCount the value for unqualify_apply.unqualify_count
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setUnqualifyCount(Integer unqualifyCount) {
        this.unqualifyCount = unqualifyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualify_apply.assembly_date
     *
     * @return the value of unqualify_apply.assembly_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getAssemblyDate() {
        return assemblyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualify_apply.assembly_date
     *
     * @param assemblyDate the value for unqualify_apply.assembly_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setAssemblyDate(Date assemblyDate) {
        this.assemblyDate = assemblyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualify_apply.emp_id
     *
     * @return the value of unqualify_apply.emp_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualify_apply.emp_id
     *
     * @param empId the value for unqualify_apply.emp_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualify_apply.apply_date
     *
     * @return the value of unqualify_apply.apply_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualify_apply.apply_date
     *
     * @param applyDate the value for unqualify_apply.apply_date
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unqualify_apply.note
     *
     * @return the value of unqualify_apply.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unqualify_apply.note
     *
     * @param note the value for unqualify_apply.note
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}