package cn.com.taiji.domain;

import javax.validation.constraints.Size;

public class Work {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.work_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max=40, message="{id.length.error}")
    private String workId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.process_number
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max=40, message="工序号的长度限制在40个字符之内")
    private String processNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.product_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max=40, message="{id.length.error}")
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.process_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max=40, message="{id.length.error}")
    private String processId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.device_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    @Size(max=40, message="{id.length.error}")
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.rating
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    private Integer rating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.work_id
     *
     * @return the value of work.work_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.work_id
     *
     * @param workId the value for work.work_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.process_number
     *
     * @return the value of work.process_number
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getProcessNumber() {
        return processNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.process_number
     *
     * @param processNumber the value for work.process_number
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setProcessNumber(String processNumber) {
        this.processNumber = processNumber == null ? null : processNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.product_id
     *
     * @return the value of work.product_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.product_id
     *
     * @param productId the value for work.product_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.process_id
     *
     * @return the value of work.process_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.process_id
     *
     * @param processId the value for work.process_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setProcessId(String processId) {
        this.processId = processId == null ? null : processId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.device_id
     *
     * @return the value of work.device_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.device_id
     *
     * @param deviceId the value for work.device_id
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.rating
     *
     * @return the value of work.rating
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.rating
     *
     * @param rating the value for work.rating
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }
}