package cn.com.taiji.mapper;

import cn.com.taiji.domain.COrder;
import cn.com.taiji.domain.COrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface COrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(COrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(COrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(COrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(COrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<COrder> selectByExample(COrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    COrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") COrder record, @Param("example") COrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") COrder record, @Param("example") COrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(COrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(COrder record);
}