package cn.com.taiji.mapper;

import cn.com.taiji.domain.DeviceCheck;
import cn.com.taiji.domain.DeviceCheckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(DeviceCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(DeviceCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String deviceCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(DeviceCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(DeviceCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<DeviceCheck> selectByExample(DeviceCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    DeviceCheck selectByPrimaryKey(String deviceCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") DeviceCheck record, @Param("example") DeviceCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") DeviceCheck record, @Param("example") DeviceCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(DeviceCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(DeviceCheck record);
}