package cn.com.taiji.mapper;

import cn.com.taiji.domain.DeviceCheck;
import cn.com.taiji.domain.DeviceCheckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(DeviceCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(DeviceCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String deviceCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(DeviceCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(DeviceCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<DeviceCheck> selectByExample(DeviceCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    DeviceCheck selectByPrimaryKey(String deviceCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") DeviceCheck record, @Param("example") DeviceCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") DeviceCheck record, @Param("example") DeviceCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(DeviceCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(DeviceCheck record);

    //扩展的mapper接口方法
    List<DeviceCheck> find(DeviceCheck deviceCheck);

    int deleteBatch(String[] deviceCheckIds);

    //根据设备id查找设备例检信息
    List<DeviceCheck> searchDeviceCheckByDeviceCheckId(String deviceCheckId);

    //根据设备名称查找设备例检信息
    List<DeviceCheck> searchDeviceCheckByDeviceName(String deviceName);

    int updateNote(DeviceCheck deviceCheck);
}