package cn.com.taiji.mapper;

import cn.com.taiji.domain.DeviceMaintain;
import cn.com.taiji.domain.DeviceMaintainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceMaintainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintain
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(DeviceMaintainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintain
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(DeviceMaintainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintain
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String deviceMaintainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintain
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(DeviceMaintain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintain
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(DeviceMaintain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintain
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<DeviceMaintain> selectByExample(DeviceMaintainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintain
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    DeviceMaintain selectByPrimaryKey(String deviceMaintainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintain
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") DeviceMaintain record, @Param("example") DeviceMaintainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintain
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") DeviceMaintain record, @Param("example") DeviceMaintainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintain
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(DeviceMaintain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_maintain
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(DeviceMaintain record);

    //扩展的mapper接口方法
    List<DeviceMaintain> find(DeviceMaintain deviceMaintain);

    int updateNote(DeviceMaintain deviceMaintain);

    int deleteBatch(String[] DeviceMaintainIds);

    //根据设备维修id查找设备维修信息
    List<DeviceMaintain> searchDeviceMaintainByDeviceMaintainId(String deviceMaintainId);

    //根据设备故障id查找设备维修信息
    List<DeviceMaintain> searchDeviceMaintainByDeviceFaultId(String deviceFaultId);
}