package cn.com.taiji.mapper;

import cn.com.taiji.domain.DeviceFault;
import cn.com.taiji.domain.DeviceFaultExample;
import java.util.List;

import cn.com.taiji.domain.vo.DeviceFaultVO;
import org.apache.ibatis.annotations.Param;

public interface DeviceFaultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_fault
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(DeviceFaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_fault
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(DeviceFaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_fault
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String deviceFaultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_fault
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(DeviceFault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_fault
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(DeviceFault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_fault
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<DeviceFault> selectByExample(DeviceFaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_fault
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    DeviceFault selectByPrimaryKey(String deviceFaultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_fault
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") DeviceFault record, @Param("example") DeviceFaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_fault
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") DeviceFault record, @Param("example") DeviceFaultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_fault
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(DeviceFault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_fault
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(DeviceFault record);

    /*
    *   用户自定义mapper接口
    * */

    List<DeviceFaultVO> find(DeviceFault deviceFault);

    List<DeviceFault> getData();

    int deleteBatch(String[] deviceFaultIds);

    int updateNote(DeviceFault deviceFault);

    List<DeviceFault> searchDeviceFaultByDeviceFaultId(String deviceFaultId);

    List<DeviceFault> searchDeviceFaultByDeviceName(String deviceName);
}