package cn.com.taiji.mapper;

import cn.com.taiji.domain.Employee;
import cn.com.taiji.domain.EmployeeExample;
import java.util.List;

import cn.com.taiji.domain.vo.EmployeeVO;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Mon Jan 28 09:51:23 CST 2019
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Mon Jan 28 09:51:23 CST 2019
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Mon Jan 28 09:51:23 CST 2019
     */
    int deleteByPrimaryKey(String empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Mon Jan 28 09:51:23 CST 2019
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Mon Jan 28 09:51:23 CST 2019
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Mon Jan 28 09:51:23 CST 2019
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Mon Jan 28 09:51:23 CST 2019
     */
    Employee selectByPrimaryKey(String empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Mon Jan 28 09:51:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Mon Jan 28 09:51:23 CST 2019
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Mon Jan 28 09:51:23 CST 2019
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Mon Jan 28 09:51:23 CST 2019
     */
    int updateByPrimaryKey(Employee record);

    //自定义mapper接口

    EmployeeVO selectSingleEmployee(String empId);

    List<EmployeeVO> find();

    int deleteBatch(String[] ids);

    List<EmployeeVO> searchEmployeeByEmployeeId(String employeeId);

    List<EmployeeVO> searchEmployeeByEmployeeName(String employeeName);

    List<EmployeeVO> searchEmployeeByDepartmentName(String departmentName);
}