package cn.com.taiji.mapper;

import cn.com.taiji.domain.FinalCountCheck;
import cn.com.taiji.domain.FinalCountCheckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FinalCountCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(FinalCountCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(FinalCountCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String fCountCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(FinalCountCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(FinalCountCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<FinalCountCheck> selectByExample(FinalCountCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    FinalCountCheck selectByPrimaryKey(String fCountCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") FinalCountCheck record, @Param("example") FinalCountCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") FinalCountCheck record, @Param("example") FinalCountCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(FinalCountCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table final_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(FinalCountCheck record);
}