package cn.com.taiji.mapper;

import cn.com.taiji.domain.Manufacture;
import cn.com.taiji.domain.ManufactureExample;
import java.util.List;

import cn.com.taiji.domain.vo.ManufactureVO;
import org.apache.ibatis.annotations.Param;

public interface ManufactureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(ManufactureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(ManufactureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String manufactureSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(Manufacture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(Manufacture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<ManufactureVO> selectByExample(ManufactureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    ManufactureVO selectByPrimaryKey(String manufactureSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Manufacture record, @Param("example") ManufactureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") Manufacture record, @Param("example") ManufactureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(Manufacture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacture
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(Manufacture record);


    /*
    *   自定义mapper接口
    * */
    
    List<ManufactureVO> find();

    int deleteBatch(String[] ids);

    List<ManufactureVO> searchManufactureByManufactureSn(String manufactureSn);

    List<ManufactureVO> searchManufactureByManufactureOrderId(String manufactureOrderId);

    List<ManufactureVO> searchManufactureByManufactureTechnologyName(String manufactureTechnologyName);
}