package cn.com.taiji.mapper;

import cn.com.taiji.domain.ProcessMeasureCheck;
import cn.com.taiji.domain.ProcessMeasureCheckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcessMeasureCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_measure_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(ProcessMeasureCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_measure_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(ProcessMeasureCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_measure_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String pMeasureCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_measure_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(ProcessMeasureCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_measure_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(ProcessMeasureCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_measure_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<ProcessMeasureCheck> selectByExample(ProcessMeasureCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_measure_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    ProcessMeasureCheck selectByPrimaryKey(String pMeasureCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_measure_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProcessMeasureCheck record, @Param("example") ProcessMeasureCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_measure_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") ProcessMeasureCheck record, @Param("example") ProcessMeasureCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_measure_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(ProcessMeasureCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_measure_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(ProcessMeasureCheck record);
}