package cn.com.taiji.mapper;

import cn.com.taiji.domain.ProcessCountCheck;
import cn.com.taiji.domain.ProcessCountCheckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcessCountCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(ProcessCountCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(ProcessCountCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String pCountCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(ProcessCountCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(ProcessCountCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<ProcessCountCheck> selectByExample(ProcessCountCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    ProcessCountCheck selectByPrimaryKey(String pCountCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProcessCountCheck record, @Param("example") ProcessCountCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") ProcessCountCheck record, @Param("example") ProcessCountCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(ProcessCountCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process_count_check
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(ProcessCountCheck record);
}