package cn.com.taiji.mapper;

import cn.com.taiji.domain.Technology;
import cn.com.taiji.domain.TechnologyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TechnologyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(TechnologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(TechnologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String technologyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(Technology record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(Technology record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<Technology> selectByExample(TechnologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    Technology selectByPrimaryKey(String technologyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Technology record, @Param("example") TechnologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") Technology record, @Param("example") TechnologyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(Technology record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(Technology record);
}