package cn.com.taiji.mapper;

import cn.com.taiji.domain.TechnologyPlan;
import cn.com.taiji.domain.TechnologyPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TechnologyPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(TechnologyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(TechnologyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String technologyPlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(TechnologyPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(TechnologyPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<TechnologyPlan> selectByExample(TechnologyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    TechnologyPlan selectByPrimaryKey(String technologyPlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") TechnologyPlan record, @Param("example") TechnologyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") TechnologyPlan record, @Param("example") TechnologyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(TechnologyPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_plan
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(TechnologyPlan record);
}