package cn.com.taiji.mapper;

import cn.com.taiji.domain.TechnologyRequirement;
import cn.com.taiji.domain.TechnologyRequirementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TechnologyRequirementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_requirement
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(TechnologyRequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_requirement
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(TechnologyRequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_requirement
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String technologyRequirementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_requirement
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(TechnologyRequirement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_requirement
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(TechnologyRequirement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_requirement
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<TechnologyRequirement> selectByExample(TechnologyRequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_requirement
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    TechnologyRequirement selectByPrimaryKey(String technologyRequirementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_requirement
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") TechnologyRequirement record, @Param("example") TechnologyRequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_requirement
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") TechnologyRequirement record, @Param("example") TechnologyRequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_requirement
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(TechnologyRequirement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table technology_requirement
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(TechnologyRequirement record);
}