package cn.com.taiji.mapper;

import cn.com.taiji.domain.UnqualifyApply;
import cn.com.taiji.domain.UnqualifyApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UnqualifyApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualify_apply
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    long countByExample(UnqualifyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualify_apply
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByExample(UnqualifyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualify_apply
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int deleteByPrimaryKey(String unqualifyApplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualify_apply
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insert(UnqualifyApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualify_apply
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int insertSelective(UnqualifyApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualify_apply
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    List<UnqualifyApply> selectByExample(UnqualifyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualify_apply
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    UnqualifyApply selectByPrimaryKey(String unqualifyApplyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualify_apply
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") UnqualifyApply record, @Param("example") UnqualifyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualify_apply
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByExample(@Param("record") UnqualifyApply record, @Param("example") UnqualifyApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualify_apply
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKeySelective(UnqualifyApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unqualify_apply
     *
     * @mbg.generated Fri Jan 25 11:46:10 CST 2019
     */
    int updateByPrimaryKey(UnqualifyApply record);
}